name       : rxvt-unicode
version    : '9.24'
release    : 6
source     :
    - https://github.com/mcritchlow/rxvt-unicode/archive/rxvt-unicode-rel-9.24.tar.gz : 67164b322f4916d61bddd4c0e05f745cfa269e7eda7f3afd5f390c9f850efa51
license    : GPL-2.0
summary    : Unicode compliant fork of rxvt, commonly refered to as urxvt
component  : utils
description: |
    Unicode compliant fork of rxvt, commonly refered to as urxvt
builddeps  :
    - pkgconfig(fontconfig)
    - pkgconfig(gdk-pixbuf-2.0)
    - pkgconfig(x11)
    - pkgconfig(xft)
    - pkgconfig(xrender)
patterns   :
    - /usr/share/man
setup      : |
    %patch -p1 < $pkgfiles/font-width.patch
    %configure --enable-256-color \
               --enable-combining \
               --enable-xft \
               --enable-font-styles \
               --enable-pixbuf \
               --enable-startup-notification \
               --enable-transparency \
               --enable-fading \
               --enable-rxvt-scroll \
               --enable-mousewheel \
               --enable-slipwheeling \
               --enable-smart-resize \
               --enable-text-blink \
               --enable-unicode3 \
               --enable-pointer-blank \
               --enable-utmp \
               --enable-wtmp \
               --enable-lastlog
build      : |
    %make
install    : |
    %make_install
