name       : rxvt-unicode
version    : 9.21
release    : 1
source     :
    - http://dist.schmorp.de/rxvt-unicode/rxvt-unicode-9.21.tar.bz2 : 75270ed72bc5895a64a1d7392bf45a622204192371c3965bd3dd978dc088956b
license    : GPL-2.0
summary    : Unicode compliant fork of rxvt, commonly refered to as urxvt
description: |
    Unicode compliant fork of rxvt, commonly refered to as urxvt
builddeps  :
    - pkgconfig(x11)
patterns   :
    - /usr/share/man
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
