name       : rxvt-unicode
version    : 9.21
release    : 2
source     :
    - http://dist.schmorp.de/rxvt-unicode/rxvt-unicode-9.21.tar.bz2 : 75270ed72bc5895a64a1d7392bf45a622204192371c3965bd3dd978dc088956b
license    : GPL-2.0
summary    : Unicode compliant fork of rxvt, commonly refered to as urxvt
description: |
    Unicode compliant fork of rxvt, commonly refered to as urxvt
builddeps  :
    - pkgconfig(x11)
    - pkgconfig(xft)
    - pkgconfig(xrender)
    - pkgconfig(gdk-pixbuf-2.0)
    - pkgconfig(fontconfig)
patterns   :
    - /usr/share/man
setup      : |
    %configure --enable-256-color \
               --enable-combining \
               --enable-xft \
               --enable-font-styles \
               --enable-pixbuf \
               --enable-startup-notification \
               --enable-transparency \
               --enable-fading \
               --enable-rxvt-scroll \
               --enable-mousewheel \
               --enable-slipwheeling \
               --enable-smart-resize \
               --enable-text-blink \
               --enable-pointer-blank \
               --enable-utmp \
               --enable-wtmp \
               --enable-lastlog               
build      : |
    %make
install    : |
    %make_install
